### ISSUE TITLE
Parameterize Dataloader config and document its use

### ISSUE THREAD

**Issue by biphasic** [nc-fortiss/2024-nc-hackathon-AstroSpikes#8]
Use [OmegaConf](https://omegaconf.readthedocs.io/en/2.1_branch/usage.html#from-a-yaml-file)

**Comment by MaxPlanck336** [comment]
Completed
Config file at: 2024-nc-hackathon-spades/conf/data_loader_conf.yaml
Documentation for config file at: 2024-nc-hackathon-spades/conf/guide.md
